apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: <TENANT_NAME>-dev
  namespace: openshift-gitops
spec:
  destination:
    namespace: <TENANT_NAME>-dev
    server: 'https://kubernetes.default.svc'
  source:
    path: 01-<TENANT_NAME>/00-argocd-apps/01-dev/
    repoURL: 'https://gitlab.apps.devtest.vxdqgl7u.kubeapp.cloud/<TENANT_NAME>/apps-gitops-config.git'
    targetRevision: main
    directory:
       recurse: true
  project: <TENANT_NAME>
  syncPolicy:
    automated:
      prune: true
      selfHeal: true